#!/bin/bash
#
# Skript zur automatischen Installation des Miranda Automaten-Pakets
# im Miranda-Systemverzeichnis - es muss bei der ersten Installation
# als root ausgeführt werden, sonst genügen Standard-Benutzerrechte.
#
# (c) Oliver Schäfer, FU-Berlin, im Februar 2018

LWBMIRALIB=/usr/lib/miralib/lwb

MAKELIST="automaten.m automatentools.m automatentoolsimpl.m ansiseq.m ra.m loop.m while.m goto.m"
FILELIST="automaten*.m ansiseq.m ra*.m README.md loop.m while.m goto.m"
OWNLIST="automaten* ansiseq* ra* loop.m goto.m while.m"

if [ ! -d $LWBMIRALIB ]; then
  if [ $UID != 0 ]; then
    echo "Skript muss als root ausgeführt werden!"
    exit 1
  else
    mkdir $LWBMIRALIB
    chown lewein:lewein $LWBMIRALIB
  fi
else
  if [ ! -O $LWBMIRALIB ] && [ $UID != 0 ]; then
    echo "Skript muss als root ausgeführt werden!"
    exit 1
  else
    chown lewein:lewein $LWBMIRALIB
  fi
fi

cp $FILELIST $LWBMIRALIB/
cd $LWBMIRALIB
mira -make $MAKELIST
chown lewein:lewein $OWNLIST

echo "installation des Automaten- RA-Paket und Berechenbarkeitpakets erfolgreich!"
