#!/bin/bash
# Skript zur automatischen Installation des Miranda Automaten-Pakets
# im Miranda-Systemverzeichnis - es muss als root ausgeführt werden!

# (c) Oliver Schäfer, FU-Berlin, 17.02.2016

LWBMIRALIB=/usr/lib/miralib/lwb
MAKELIST="automaten.m automatentools.m automatentoolsimpl.m ansiseq.m"
FILELIST="automaten.m automatenimpl.m automatentools.m automatentoolsimpl.m ansiseq.m"

if [ ! -d $LWBMIRALIB ]; then
  if [ $UID != 0 ]; then
    echo "Skript muss als root ausgeführt werden!"
    exit 1
  else
    mkdir $LWBMIRALIB
    chown lewein:lewein $LWBMIRALIB
  fi
fi

cp $FILELIST $LWBMIRALIB/
cd $LWBMIRALIB
mira -make $MAKELIST
chown lewein:lewein automaten* ansiseq*

echo "installation des Automaten-Pakets erfolgreich!"
